# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.8'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=artist_management_meher
            - MYSQL_USER=user
        web:
            build: .
            ports:
            - 8000:80
    
