version: '3'

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./database/:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - database

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app/:/var/www/app
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            JWT_PASSPHRASE: ${JWT_PASSPHRASE}
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"
        depends_on:
            - db
        networks:
            - server
            - database
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/backend/
        ports:
            - ${NGINX_PORT}:80
        depends_on:
            - php
        networks:
            - server

networks:
    database:
    server: