api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:     ['application/merge-patch+json','application/json']
        jsonapi:  ['application/vnd.api+json','application/json']
    swagger:
        versions: [3]
