<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWApLJ7c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWApLJ7c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWApLJ7c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWApLJ7c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWApLJ7c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WApLJ7c',
    'container.build_id' => '25ba2dd1',
    'container.build_time' => 1634590797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWApLJ7c');
